<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerKxBcId9\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerKxBcId9/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerKxBcId9.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerKxBcId9\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerKxBcId9\App_KernelDevDebugContainer([
    'container.build_hash' => 'KxBcId9',
    'container.build_id' => '18d9fe4b',
    'container.build_time' => 1615968507,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerKxBcId9');
