<?php

// This file has been auto-generated by the Symfony Cache Component.

return [[

'_default' => 0,

], [

0 => [
    'entrypoints' => [
        'app' => [
            'js' => [
                '/build/runtime.js',
                '/build/vendors~addChambre~app~delete~index~tableChambre.js',
                '/build/vendors~app.js',
                '/build/app.js',
            ],
            'css' => [
                '/build/vendors~app.css',
                '/build/app.css',
            ],
        ],
        'index' => [
            'js' => [
                '/build/runtime.js',
                '/build/vendors~addChambre~app~delete~index~tableChambre.js',
                '/build/index.js',
            ],
        ],
        'addChambre' => [
            'js' => [
                '/build/runtime.js',
                '/build/vendors~addChambre~app~delete~index~tableChambre.js',
                '/build/addChambre.js',
            ],
        ],
        'tableChambre' => [
            'js' => [
                '/build/runtime.js',
                '/build/vendors~addChambre~app~delete~index~tableChambre.js',
                '/build/tableChambre.js',
            ],
        ],
        'delete' => [
            'js' => [
                '/build/runtime.js',
                '/build/vendors~addChambre~app~delete~index~tableChambre.js',
                '/build/vendors~delete.js',
                '/build/delete.js',
            ],
        ],
    ],
],

]];
